Clean up DAP4 code plus minor mods to other, non-dap4, code; second attempt.
Unidata/netcdf-java pull request #1152
Opened 2023-02-27 01:58 UTC by DennisHeimbigner

## Description of Changes

This PR make major changes to the DAP4 code. It also makes some small but necessary changes to non-DAP4 code, the nature of which will be described in some detail below.

## DAP4 Module Changes

* Biggest change is to merge all of the dap submodules (dap4:d4core, dap4:d4cdm, etc) into just one single "dap4" module.
* Get rid of the old DAP4 CDMXXX types and instead use the standard netcdf-java Array and Index types; this has some consequences with respect to what kind of sequence objects can be handled.
* Reduce the set of DAP4 tests to be similar to those used by netcdf-c.
* Convert tests to JUNIT-4 parameterized tests.
  - Move various files around in the module
* Remove all tests that use server mocking -- we will use a real server instead.
* Modify dap4/build.gradle:
  - Remove out-of-date comments
  - Switch compile action in dap4 build.gradle to implementation in anticipation of a gradle version upgrade.
  - Conform to the re-organized dap4 module structure, including tests.
* Aggregate (almost) all DAP4 constants into DapConstants.java.
* Remove unused code
* Move some DAP4 only code from UnitTestCommon.java to DapTestCommon.java
* Begin the conversion to the new checksum mode capability.
  - Move various files around in the module
* Remove the now unused Bison-based DMR parser.
* Remove the Odometer code as no longer used.
* A number of classes were renamed to more accurately reflect their semantics. Specifically:
  - *DataCursor* -> *D4Array*
  - *DataIndex* -> *D4Index*
* Major code refactoring was done:
  - Added *ArrayScheme*
  - Deleted a whole raft of files
  - Delete whole DSP subsystem.
  - Move various files around in the module
* Move the ucar.nc2.dataset.spi.NetcdfFileProvider file
## DAP4 Related Changes Outside of DAP4 Module
* Enable inclusion of dap4 in fatJars and ncIdv.
* Get the HttpServices interceptor mechanism to work again; this is for debugging
* Fix DatasetUrl.checkIfDap4:
  - Properly handle the possible DAP4 extensions (like *.dsr.xml*)
  - Read the DSR to detect a DAP4 url
* Add a test to verify that the possible legal urls are recognized as being ServiceType.DAP.

## Non-DAP4 related Changes
* Move selected NetCDF-4 related constants from Attribute.java to CDM.java
* Remove extraneous code from TestCDF5Reading.java
* Clean up UnitTestCommon.java 
* Allow zero-length dimensions, but also ignore any variables that have a zero length dimension.
* Change NetcdfFiles warning from mentioning H5iop to H5iospNew.
* Fix a nullpointerexception in HTTPSession.java
* Fix TestReadArrayStructure because it was using a old path that changed as part of this PR.
* Minor comment changes

## TODO
* Search and destroy unused imports

## PR Checklist

- [X] Link to any issues that the PR addresses
- [ ] Add labels
- [ ] Open as a [draft PR](https://github.blog/2019-02-14-introducing-draft-pull-requests/) until ready for review
- [X] Make sure GitHub tests pass
- [X] Make sure Jenkins tests pass
- [X] Mark PR as "Ready for Review"

2023-03-02 16:38 UTC, haileyajohnson commented
I'm going to wait for #1151 to be finished and merged before reviewing this one :)

2023-05-25 19:15 UTC, rschmunk commented
What is the latest on when or if this pull request might be approved?

I've just had a query from developers at GSFC/GES/DISC about problems trying to access data on their DAP4 server using Panoply.

2023-06-05 21:57 UTC, haileyajohnson approved these changes
Minor comments, I don't see anything critical to change. I mostly looked at the code changes outside the DAP4 subproject. My main nitpick it all the places where `public static` has been changed to `static public`, which is the wrong order by Java standards.
Also using this PR as a reminder to myself to work on creating a tests data repo for the netcdf projects...

2023-06-05 21:57 UTC, haileyajohnson commented on cdm/core/src/main/java/ucar/nc2/Attribute.java
> -  /** @deprecated move to jni.Nc4Iosp */
We can't remove these until we're releasing a new major version

2023-06-05 21:57 UTC, haileyajohnson commented on cdm/core/src/test/java/ucar/nc2/TestSpecialAttributes.java
> +import ucar.nc2.iosp.netcdf4.Nc4;
unused?

2023-06-05 21:57 UTC, haileyajohnson commented on dap4/src/main/java/dap4/core/dmr/DapGroup.java
> +          if (false) {
what is this for?

2023-06-05 21:57 UTC, haileyajohnson commented on dap4/src/main/java/dap4/core/util/DapUtil.java
> +  static public String fqnSuffix(String fqn) {
These were all correct before: https://docs.oracle.com/javase/specs/jls/se7/html/jls-8.html#jls-8.4.3

2023-06-05 21:57 UTC, haileyajohnson commented on docs/src/site/pages/netcdfJava/developer/DatasetUrls.md
the docset that we serve is actually under pages/netcdfJava/userguide

2023-06-06 19:09 UTC, DennisHeimbigner commented on docs/src/site/pages/netcdfJava/developer/DatasetUrls.md
I was not aware that as of Java 1.8, that there was a convention in the Java specification for the ordering of modifiers. That seems reasonable to me. It would be nice if spotify enforced that convention.
Are there other conventions (other than our spotify) that you use? Perhaps a written list somewhere?
Also, I suspect that there are some other modifier issues with respect to e.g. "protected".
In any case, lets get this PR merged and I will I will go thru the code and fix all of the "static public" cases as a separate PR.

2023-06-06 19:45 UTC, haileyajohnson requested changes

2023-06-06 19:45 UTC, haileyajohnson commented on cdm/core/src/main/java/ucar/nc2/Attribute.java
> -  @Deprecated
Putting this method back in is the only change that is blocking merging

2023-06-07 01:46 UTC, DennisHeimbigner commented on cdm/core/src/main/java/ucar/nc2/Attribute.java
> -  @Deprecated
Fixed.

2023-06-07 18:07 UTC, haileyajohnson approved these changes

2023-06-07 18:07 UTC, merged