[5.5.3]: Fix GRIB IOSP time coords from intervals, for 2-D time datasets
Unidata/netcdf-java pull request #1248
Opened 2023-10-13 18:08 UTC by ethanrd

## Description of Changes

Fix generation of time coordinate variables from time intervals for 2-D time datasets. Ensure resulting time coordinate variables are strictly monotonically increasing. Handle when time intervals are irregular and overlapping.

See issue #1060.

## PR Checklist

- [ ] Link to any issues that the PR addresses
- [ ] Add labels
- [ ] Open as a [draft PR](https://github.blog/2019-02-14-introducing-draft-pull-requests/)
       until ready for review
- [ ] Make sure GitHub tests pass
- [ ] Mark PR as "Ready for Review"

2023-10-19 21:57 UTC, tdrwenski requested changes
I ran all the tests on Jenkins against your branch and one is failing: https://jenkins-aws.unidata.ucar.edu/view/Users/job/tara-netcdf-java/35/

In the `TestGribCompareBuilders` tests it looks like it is comparing the builder/ non-builder versions for all files in `../grib/src/test/data/` and it looks like there's a difference for the new file you added. I do not believe this is actually related to your changes (I ran the test with that file on `maint-5.x` and it also failed). Since it's unrelated and I'm not sure how important it is that the with/without builders return identical results, maybe it's easiest to just ignore that new test file in that test and possibly fix it later.

2023-10-19 21:57 UTC, tdrwenski commented on grib/src/main/java/ucar/nc2/grib/collection/GribTimeCoordIntervalUtils.java
> +
I don't believe this is being used
```suggestion
```

2023-10-19 21:57 UTC, tdrwenski commented on grib/src/main/java/ucar/nc2/grib/collection/GribTimeCoordIntervalUtils.java
> +public class GribTimeCoordIntervalUtils {
Since this is only being used in this package, we could make this package private
```suggestion
class GribTimeCoordIntervalUtils {
```

2023-10-19 21:57 UTC, tdrwenski commented on grib/src/test/java/ucar/nc2/grib/coord/TestDiscontiguousInterval.java
> +      Array reftimeValues = reftimeVar.read();
This and the below `Array`s are not used. Is there something reasonable we can assert here? Or did you just want to read them to check no exception was thrown?

2023-10-20 15:39 UTC, ethanrd commented on grib/src/main/java/ucar/nc2/grib/collection/GribTimeCoordIntervalUtils.java
> +
Yes, I added that thinking there might be situations in which we'd want to handle these different cases. Didn't find any (didn't look too hard) nor did I think too much about how to implement.

2023-10-20 15:40 UTC, ethanrd commented on grib/src/main/java/ucar/nc2/grib/collection/GribTimeCoordIntervalUtils.java
> +public class GribTimeCoordIntervalUtils {
Good idea.

2023-10-20 16:05 UTC, ethanrd commented on grib/src/test/java/ucar/nc2/grib/coord/TestDiscontiguousInterval.java
> +      Array reftimeValues = reftimeVar.read();
I think I put those in there for debugging and forgot to remove them. I don't think it's worth trying to come up with tests. The strict monotonicity of `timeOffset` is the root issue here.

2023-10-20 16:16 UTC, ethanrd commented
Agree, probably easier to ignore the new test file. Are there other test files excluded from this test?

2023-10-20 18:10 UTC, ethanrd commented on grib/src/test/java/ucar/nc2/grib/coord/TestDiscontiguousInterval.java
> +      Array reftimeValues = reftimeVar.read();
Thanks @tdrwenski ! I just pushed a change to remove the unused variable reads.

2023-10-20 18:39 UTC, tdrwenski commented
> Agree, probably easier to ignore the new test file. Are there other test files excluded from this test?

Just pushed a fix to ignore that test case!

2023-10-20 20:15 UTC, tdrwenski approved these changes

2023-10-20 21:36 UTC, merged