Service Provider for applying enhancements
Unidata/netcdf-java pull request #1369
Opened 2024-07-16 16:58 UTC by matakleo

## Description of Changes

_Erase this and add a general description of changes, heads-up on any tricky parts, etc., here._

## PR Checklist

- [ ] Link to any issues that the PR addresses
- [ ] Add labels
- [ ] Open as a [draft PR](https://github.blog/2019-02-14-introducing-draft-pull-requests/)
       until ready for review
- [ ] Make sure GitHub tests pass
- [ ] Mark PR as "Ready for Review"

2024-07-17 19:32 UTC, tdrwenski requested changes
Overall looks good, just a few minor style issues!

2024-07-17 19:32 UTC, tdrwenski commented on cdm/core/src/main/java/ucar/unidata/io/spi/EnhancementProvider.java
> +/*
Think this whole file can go-- looks like you are using the EnhancementProvider class in the filter package

2024-07-17 19:32 UTC, tdrwenski commented on cdm/core/src/main/java/ucar/nc2/filter/Classifier.java
> +import java.util.Map;
Maybe you can clean up several unused imports here-- IntelliJ should grey them out if they are not used.

2024-07-17 19:32 UTC, tdrwenski commented on cdm/core/src/main/java/ucar/nc2/dataset/VariableDS.java
> +    /** how oh how ??? */
this comment can go now I think 😆

2024-07-17 19:32 UTC, tdrwenski commented on cdm/core/src/main/java/ucar/nc2/dataset/VariableDS.java
> +        /** Stand and Norm require floatingpoint, buc classifier can do just numeric? */
this comment can go now I think

2024-07-17 19:32 UTC, tdrwenski commented on cdm/core/src/main/java/ucar/nc2/filter/ScaleOffset.java
> +    // @Override
This can go

2024-07-17 19:32 UTC, tdrwenski commented on cdm/core/src/main/java/ucar/nc2/filter/EnhancementProvider.java
> +  // void applyEnhancement(Object instance);
this can go

2024-07-17 19:32 UTC, tdrwenski commented on cdm/core/src/main/java/ucar/nc2/filter/EnhancementProvider.java
> +  Enhancement returnObject(VariableDS var);
maybe we can rename this... `createEnhancement` or maybe just `create`?

2024-07-17 19:32 UTC, tdrwenski commented on cdm/core/src/main/java/ucar/nc2/filter/Classifier.java
> +    public Classifier returnObject(VariableDS var) {
This can also have `@Override`

2024-07-17 19:32 UTC, tdrwenski commented on cdm/core/src/main/java/ucar/nc2/filter/EnhancementProvider.java
> +  String getName();
is this used?

2024-07-17 19:32 UTC, tdrwenski commented on cdm/core/src/main/java/ucar/nc2/filter/EnhancementProvider.java
> +// package ucar.nc2.dataset;
this can go

2024-07-17 19:32 UTC, tdrwenski commented on cdm/core/src/main/java/ucar/nc2/filter/EnhancementProvider.java
> + * A Service Provider of {@link Filter}.
```suggestion
 * A Service Provider of {@link Enhancement}.
```

2024-07-17 20:29 UTC, tdrwenski commented on cdm/core/src/main/java/ucar/nc2/filter/EnhancementProvider.java
> +  Enhancement Create(VariableDS var);
should start with lower case for method names in java, so let's make it `create`

2024-07-17 21:27 UTC, haileyajohnson approved these changes
This looks great!

2024-07-17 21:27 UTC, haileyajohnson commented on cdm/core/src/main/java/ucar/nc2/filter/EnhancementProvider.java
> +  Enhancement Create(VariableDS var);
+1

2024-07-17 21:27 UTC, haileyajohnson commented on cdm/core/src/main/java/ucar/nc2/filter/Classifier.java
> +
if you make another commit, remove these spaces just to keep things clean

2024-07-17 21:27 UTC, haileyajohnson commented on cdm/core/src/main/java/ucar/nc2/filter/ScaleOffset.java
>      }
no need to commit changes to this file at all it seems :)

2024-07-18 14:48 UTC, haileyajohnson approved these changes

2024-07-18 14:52 UTC, merged