Non-integral time periods in Grid
Unidata/netcdf-java pull request #821
Opened 2021-09-11 01:39 UTC by JohnLCaron

add makeFractionalCalendarDate, makeFractionalOffsetFromRefDate to CalendarDateUnit
GridTimeCoordinateSystem.getTimesForRuntimes uses makeFractionalCalendarDate
SubsetTimeHelper.subsetTime uses makeFractionalOffsetFromRefDate
port coverage tests to grid (pass 3)

2021-09-11 14:28 UTC, JohnLCaron commented
ready

2021-09-13 18:37 UTC, haileyajohnson requested changes
> Reviewed 19 of 19 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/unidata/netcdf-java/821)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnLCaron and @lesserwhirls)

___
*[cdm-core/src/test/java/ucar/nc2/calendar/TestCalendarDateUnit.java, line 75 at r1](https://reviewable.io/reviews/unidata/netcdf-java/821#-MjVQvN52tiTHhsCnlew:-MjVQvN659rypMBe_Ni8:beqlgqs) ([raw file](https://github.com/unidata/netcdf-java/blob/7104107e59614b276328451f60fe417b027630e8/cdm-core/src/test/java/ucar/nc2/calendar/TestCalendarDateUnit.java#L75)):*
> ```Java
>     } catch (Exception e) {
>       // ok
>     }
> ```

Can we change this to an `assertThrows` check instead? (assuming I'm reading this right that we expect it to throw)


<!-- Sent from Reviewable.io -->

2021-09-13 21:08 UTC, JohnLCaron commented
agree, ill start using assertThrows instead of fail()

2021-09-13 21:32 UTC, haileyajohnson approved these changes

2021-09-13 21:32 UTC, merged